version = 1

# Configuración para análisis de TypeScript/JavaScript (Backend y Frontend)
[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser"
  ]

# Configuración para análisis de SQL
[[analyzers]]
name = "sql"
enabled = true

# Configuración para análisis de secretos y credenciales
[[analyzers]]
name = "secrets"
enabled = true

# Configuración para análisis de Docker (si usas Docker)
[[analyzers]]
name = "docker"
enabled = true

# Configuración para análisis de test coverage
[[analyzers]]
name = "test-coverage"
enabled = false

# Transformers para auto-fix de problemas
[[transformers]]
name = "prettier"
enabled = false

# Exclusiones - archivos/carpetas que no se deben analizar
exclude_patterns = [
  "node_modules/**",
  "dist/**",
  "build/**",
  "coverage/**",
  "*.min.js",
  "*.bundle.js",
  "backend/prisma/migrations/**",
  "database/migraciones/**",
  "*.log",
  "*.lock",
  ".git/**",
  ".vscode/**",
  "backup_antes_limpieza/**"
]

version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]