trigger:
- main

pool:
  name: Default
  demands:
    - Agent.Name -equals DESKTOP-NUK01OF

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Instalar Node.js'

- script: |
    dir /s
    cd backend
    dir
    npm install
    npm run test
  displayName: 'Listar todo el contenido y ejecutar pruebas'